version: '3.8'

services:
  frigate:
    image: blakeblackshear/frigate:stable-amd64
    container_name: frigate
    restart: unless-stopped
    tmpfs:
      - /tmp/cache:exec,size=1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    shm_size: '64m'
    network_mode: host
    volumes:
      - /media/frigate:/media/frigate
      - /config/config.yml:/config/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_PASSWORD=password
    ports:
      - "7008:5000"
      - "1935:1935"
